language: node_js

node_js: '10'

install:
  - yarn install

jobs:
  include:
    # - stage: unit tests with coverage
    #   script: yarn coverage
    - stage: run build
      script: yarn build
    - stage: npm release
      if: NOT type IN (pull_request)
      node_js: lts/*
      script:
        - yarn build
        - npx semantic-release
      on: master
