name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@2ab6dce4f53589dada480b94c53cb05a06b04673
        with:
          version: 6.10.0

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
